# fly.toml app configuration file generated for discord-trade-logger on 2025-06-28T15:19:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-trade-logger'
primary_region = 'ord'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
